### ISSUE TITLE
Script timeout after getting the first 15 Friends

### ISSUE THREAD

**Issue by aegiz** [eleurent/twitter-graph#2]
# Description

Hey there, I have just started using  your script (great project by the way), unfortunately I am getting a timeout error after fetching the first 15 followers.

```
Found 1133 followers.
Found 1759 friends.
[1/1133] Fetching friends of @triptych
[2/1133] Fetching friends of @mintset2
[3/1133] Fetching friends of @severinebv
[4/1133] Fetching friends of @gad_maxime
[5/1133] Fetching friends of @dadideo
[6/1133] Fetching friends of @mloigeret
[7/1133] Fetching friends of @SimonHalimonov
[8/1133] Fetching friends of @AppTikki
[9/1133] Fetching friends of @Jen_Cosmo
[10/1133] Fetching friends of @sivandish
[11/1133] Fetching friends of @etienne_mineur
[12/1133] Fetching friends of @simonh
[13/1133] Fetching friends of @ShittuSaheedA3
[14/1133] Fetching friends of @devtomanager
[15/1133] Fetching friends of @tokiwoki
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 318, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fetch_data.py", line 185, in <module>
    main()
  File "fetch_data.py", line 174, in main
    friends_restricted_to=all_users)
  File "fetch_data.py", line 75, in fetch_friendships
    user_friends = api.GetFriendIDs(user_id=user["id"], stringify_ids=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twitter/api.py", line 2434, in GetFriendIDs
    total_count)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twitter/api.py", line 2338, in _GetFriendFollowerIDs
    count=count)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twitter/api.py", line 2215, in _GetIDsPaged
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twitter/api.py", line 4992, in _RequestUrl
    resp = self._session.get(url, auth=self.__auth, timeout=self._timeout, proxies=self.proxies)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=None)
```
# Steps to reproduce

After launching the script with this command
```
$ python3 fetch_data.py
```
... The script is getting the first 15 friends then stops and timeout. On rerun the script get the 15 first followers in the cache and timeout at 28.
# Expected result
I would expect the script to continue fetching friends
# Actual result
Script stopped.

# Environment
- MacOs Mojave
- pip 19.0.3
- Python 3.7.4

# More info/thoughts
None

**Comment by eleurent** [comment]
After 15 API call you timically reach the API rate limit, which either throws a `RateLimit` exception if `--stop-on-rate-limit` is enabled, or triggers a sleep of 15 minutes otherwise.

But here you get a `ReadTimeout` exception, which is a bit weird. I had similar issues when I run into some users that have hundreds of thousands of friends, which is why I add added an `excluded.json` file to avoid them, but here it doesn't seem to be the case.

Could you try again after waiting 15mn, and see if the problem can be reproduced? If not, it was probably related to the rate limit (but then idk why you did not get the proper exception)
